### ISSUE TITLE
Api doesn't respond anymore

### ISSUE THREAD

**Issue by oguzkaganeren** [manjaro-contrib/package-search#1]
@boredland Hello, did you change something? It returns empty. Could you check it in your free time?

https://search.manjaro-sway.download/?name=firefox&branch=stable
https://search.manjaro-sway.download/?name=gimp&branch=unstable

**Comment by boredland** [comment]
Perhaps the API key expired, will take a look!

**Comment by boredland** [comment]
Seems the github Index isn't working at all: https://github.com/search?q=repo%3Amanjaro-contrib%2Ftrace-mirror-dbs%20firefox&type=code

**Comment by boredland** [comment]
Tuned it a bit, so it now uses file paths and skips the whole github api whoes.

**Comment by boredland** [comment]
Heads up: with that change, the API does only return exact matches, not an list of results. Hope that suits your use-case still?

**Comment by oguzkaganeren** [comment]
Thank you, good job. Yes, After small changes, it will be worked on my side.
